# Generated by Django 6.0 on 2025-12-22 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='角色编码')),
                ('role_name', models.CharField(choices=[('ADMIN', '系统管理员'), ('GENERAL_ACCOUNTANT', '总账会计'), ('PURCHASE_ACCOUNTANT', '采购会计'), ('SALES_ACCOUNTANT', '销售会计'), ('CASHIER', '出纳'), ('ACCOUNTANT_SUPERVISOR', '会计主管'), ('EMPLOYEE', '普通员工'), ('HR_STAFF', '人事专员')], max_length=50, unique=True, verbose_name='角色名称')),
                ('role_desc', models.TextField(blank=True, null=True, verbose_name='角色描述')),
                ('related_use_cases', models.TextField(blank=True, null=True, verbose_name='关联用例（编号）')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['role_code'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, verbose_name='所属部门')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='员工编号')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users_app.role', verbose_name='所属角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'ordering': ['employee_id'],
            },
        ),
    ]
