# Generated by Django 6.0 on 2025-12-22 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_type', models.CharField(choices=[('LOGIN', '登录系统'), ('CREATE', '创建数据'), ('UPDATE', '修改数据'), ('DELETE', '删除数据'), ('AUDIT', '审核数据'), ('EXPORT', '导出数据'), ('BACKUP', '备份数据')], max_length=20, verbose_name='操作类型')),
                ('operate_module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('operate_content', models.TextField(verbose_name='操作内容')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'ordering': ['-operate_time'],
            },
        ),
    ]
