# Generated by Django 6.0 on 2025-12-22 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=30, unique=True, verbose_name='凭证编号')),
                ('voucher_date', models.DateField(default=django.utils.timezone.now, verbose_name='凭证日期')),
                ('voucher_type', models.CharField(choices=[('RECEIPT', '收款凭证'), ('PAYMENT', '付款凭证'), ('TRANSFER', '转账凭证')], max_length=20, verbose_name='凭证类型')),
                ('summary', models.CharField(max_length=200, verbose_name='凭证摘要')),
                ('maker', models.CharField(max_length=50, verbose_name='制单人')),
                ('audit_status', models.CharField(choices=[('UNCHECKED', '未审核'), ('CHECKED', '已审核'), ('REJECTED', '驳回')], default='UNCHECKED', max_length=20, verbose_name='审核状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '记账凭证',
                'verbose_name_plural': '记账凭证',
            },
        ),
        migrations.CreateModel(
            name='AccountingSubject',
            fields=[
                ('subject_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='科目编号')),
                ('subject_name', models.CharField(max_length=50, unique=True, verbose_name='科目名称')),
                ('subject_type', models.CharField(choices=[('ASSET', '资产类'), ('LIABILITY', '负债类'), ('EQUITY', '所有者权益类'), ('COST', '成本类'), ('PROFIT', '损益类')], max_length=20, verbose_name='科目类型')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('parent_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance_app.accountingsubject', verbose_name='父科目')),
            ],
            options={
                'verbose_name': '会计科目',
                'verbose_name_plural': '会计科目',
            },
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('DEBIT', '借方'), ('CREDIT', '贷方')], max_length=10, verbose_name='借贷方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
                ('detail_summary', models.CharField(blank=True, max_length=200, null=True, verbose_name='明细摘要')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_app.accountingsubject', verbose_name='会计科目')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_details', to='finance_app.voucher', verbose_name='所属凭证')),
            ],
            options={
                'verbose_name': '凭证明细',
                'verbose_name_plural': '凭证明细',
            },
        ),
    ]
