# Generated by Django 6.0 on 2025-12-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='客户ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='信用额度')),
                ('current_receivable', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='当前应收账款')),
                ('contact_info', models.JSONField(blank=True, null=True, verbose_name='联系信息')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customers',
                'ordering': ['customer_id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='供应商ID')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('payment_terms', models.CharField(blank=True, max_length=50, null=True, verbose_name='付款条件')),
                ('current_payable', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='当前应付账款')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='银行账号')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'suppliers',
                'ordering': ['supplier_id'],
            },
        ),
        migrations.RemoveField(
            model_name='voucherdetail',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='voucherdetail',
            name='voucher',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='科目代码')),
                ('account_name', models.CharField(max_length=100, verbose_name='科目名称')),
                ('account_type', models.CharField(choices=[('ASSET', '资产类'), ('LIABILITY', '负债类'), ('EQUITY', '所有者权益类'), ('COST', '成本类'), ('PROFIT', '损益类')], max_length=20, verbose_name='科目类型')),
                ('balance_direction', models.CharField(choices=[('DEBIT', '借方'), ('CREDIT', '贷方')], max_length=10, verbose_name='余额方向')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='finance_app.account', verbose_name='父级科目')),
            ],
            options={
                'verbose_name': '会计科目',
                'verbose_name_plural': '会计科目',
                'db_table': 'accounts',
                'ordering': ['account_code'],
            },
        ),
        migrations.DeleteModel(
            name='AccountingSubject',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.DeleteModel(
            name='VoucherDetail',
        ),
    ]
