# Generated by Django 6.0 on 2025-12-23 06:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_customer_supplier_remove_voucherdetail_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=6, unique=True, verbose_name='会计期间')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='生成日期')),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='资产总计')),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='负债总计')),
                ('total_equity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='所有者权益总计')),
                ('is_balanced', models.BooleanField(default=False, verbose_name='是否平衡')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
            ],
            options={
                'verbose_name': '资产负债表',
                'verbose_name_plural': '资产负债表',
                'db_table': 'balance_sheet',
            },
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=6, unique=True, verbose_name='会计期间')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='生成日期')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='营业收入')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='营业成本')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='期间费用')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='毛利润')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='净利润')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
            ],
            options={
                'verbose_name': '利润表',
                'verbose_name_plural': '利润表',
                'db_table': 'income_statement',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_id', models.CharField(max_length=20, unique=True, verbose_name='凭证编号')),
                ('voucher_date', models.DateField(default=django.utils.timezone.now, verbose_name='凭证日期')),
                ('description', models.TextField(verbose_name='摘要')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='借方总额')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='贷方总额')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('AUDITED', '已审核'), ('POSTED', '已过账')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='制单人')),
            ],
            options={
                'verbose_name': '会计凭证',
                'verbose_name_plural': '会计凭证',
                'db_table': 'vouchers',
                'ordering': ['-voucher_date', 'voucher_id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('DEBIT', '借方'), ('CREDIT', '贷方')], max_length=10, verbose_name='方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_app.account', verbose_name='会计科目')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_app.customer', verbose_name='客户')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_app.supplier', verbose_name='供应商')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance_app.voucher', verbose_name='所属凭证')),
            ],
            options={
                'verbose_name': '分录明细',
                'verbose_name_plural': '分录明细',
                'db_table': 'journal_entries',
                'ordering': ['voucher', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=6, verbose_name='会计期间')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='期初余额')),
                ('opening_direction', models.CharField(choices=[('DEBIT', '借方'), ('CREDIT', '贷方')], default='DEBIT', max_length=10, verbose_name='期初方向')),
                ('debit_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='本期借方')),
                ('credit_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='本期贷方')),
                ('ending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='期末余额')),
                ('ending_direction', models.CharField(choices=[('DEBIT', '借方'), ('CREDIT', '贷方')], default='DEBIT', max_length=10, verbose_name='期末方向')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.account', verbose_name='科目')),
            ],
            options={
                'verbose_name': '总分类账',
                'verbose_name_plural': '总分类账',
                'db_table': 'general_ledger',
                'unique_together': {('period', 'account')},
            },
        ),
    ]
