# Generated by Django 6.0 on 2025-12-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_balancesheet_incomestatement_voucher_journalentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='供应商'),
        ),
    ]
