# Generated by Django 6.0 on 2025-12-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_alter_journalentry_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='current_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='当前应付账款'),
        ),
    ]
