# Generated by Django 6.0 on 2025-12-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_alter_supplier_current_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_receivable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='当前应收账款'),
        ),
    ]
