# Generated by Django 6.0 on 2025-12-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_alter_customer_current_receivable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='联系信息'),
        ),
    ]
