# Generated by Django 6.0 on 2025-12-23 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0007_alter_customer_contact_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancesheet',
            options={'ordering': ['-period'], 'verbose_name': '资产负债表', 'verbose_name_plural': '资产负债表'},
        ),
        migrations.AlterModelOptions(
            name='incomestatement',
            options={'ordering': ['-period'], 'verbose_name': '利润表', 'verbose_name_plural': '利润表'},
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='total_cost',
            new_name='operating_cost',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='total_expense',
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='balance_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='平衡差额'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='current_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='流动资产'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='current_liabilities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='流动负债'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='current_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='本期利润'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='fixed_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='固定资产'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='intangible_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='无形资产'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='是否定稿'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='long_term_liabilities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='长期负债'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='other_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='其他资产'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='paid_in_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='实收资本'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='retained_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='留存收益'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='admin_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='管理费用'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='financial_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='财务费用'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='是否定稿'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='operating_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='营业利润'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='operating_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='营业收入'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='其他支出'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='other_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='其他收益'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='other_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='其他收入'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='profit_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='利润总额'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='selling_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='销售费用'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='tax_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='所得税费用'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='total_cost_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='成本费用总计'),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='生成日期'),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='生成日期'),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='收入总计'),
        ),
        migrations.AlterModelTable(
            name='balancesheet',
            table='balance_sheets',
        ),
        migrations.AlterModelTable(
            name='incomestatement',
            table='income_statements',
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_code', models.CharField(max_length=6, unique=True, verbose_name='期间代码')),
                ('period_name', models.CharField(max_length=50, verbose_name='期间名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('is_closed', models.BooleanField(default=False, verbose_name='是否已结账')),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='结账日期')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='结账人')),
            ],
            options={
                'verbose_name': '报表期间',
                'verbose_name_plural': '报表期间',
                'db_table': 'report_periods',
                'ordering': ['-period_code'],
            },
        ),
    ]
